# <center>Week 5: Letters Dataset</center>
| **Course:** | **Instructor:** | **Full Name:**| **Student ID:** |**Date:**  |**Term**|
| ----------- | -------------- | ---------------| ----------------|-------    |---------|
| ALY6020     | Prof. Chinthaka Pathum Dinesh Herath Gedara  | Abhilash Dikshit| 002702209       |Feb 13, 2024|Winter |

Problem:

A school is trying to decide if they can use a writing test to understand which students may need to work on their motor skills at a young age. They are testing this by having them write numbers and they want us to build a model to see if we can predict what they’ve drawn. To accomplish this, they want you to use a simplistic approach (KNN) to start the research but also compare the results with something more complicated like neural networks to accomplish this week’s task. In theory, if the model can clearly identify what a number is, that may help us point out students that need more help. Using the following dataset, complete the project.

Part 1:

Build a KNN model to predict handwriting correctly. Discuss the accuracy that you found and some of the challenges involved with using KNN for this model.

Part 2:

Build a neural network model to predict handwriting. Discuss the accuracy and some of the challenges that you had.

Part 3:

Using multiple benchmarking metrics to compare and contrast both models. Summarize your findings and suggest a final model for the school to use.

In [1]:
import pandas as pd

In [2]:
# Load the dataset
path = '~/GitProjects/Datasets/letters.csv'
df = pd.read_csv(path)
display(df)

,label,pixel43,pixel44,pixel92,pixel124,pixel125,pixel126,pixel127,pixel128,pixel129,...,pixel329,pixel351,pixel410,pixel411,pixel412,pixel413,pixel414,pixel415,pixel416,pixel417
0,1,0,0,0,0,0,0,0,0,0,...,0,254,0,0,0,0,0,0,0,0
1,0,0,0,0,137,137,192,86,72,1,...,254,0,0,75,254,254,254,17,0,0
2,1,0,0,0,3,141,139,3,0,0,...,0,184,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,94,255,69,0,0,0,0,0
4,0,0,0,0,155,254,254,254,157,30,...,253,0,0,0,223,253,253,253,129,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,2,0,0,1,248,253,176,43,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,0,0,0,0,0,0,0,0,0,128,...,0,0,0,0,255,255,0,0,0,0
41997,2,0,0,0,255,255,191,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,2,0,0,0,255,128,0,0,0,0,...,0,255,0,0,0,0,0,0,0,0
41999,2,0,0,227,253,229,133,19,0,0,...,0,0,253,160,1,0,0,0,0,0

# Part 1: Building a KNN Model

### Exploratory Data Analysis

In [3]:
info_df = pd.DataFrame({
    'Data Type': df.dtypes,
    'NA Count': df.isna().sum()
})

print(info_df)

         Data Type  NA Count
label        int64         0
pixel43      int64         0
pixel44      int64         0
pixel92      int64         0
pixel124     int64         0
pixel125     int64         0
pixel126     int64         0
pixel127     int64         0
pixel128     int64         0
pixel129     int64         0
pixel130     int64         0
pixel131     int64         0
pixel132     int64         0
pixel133     int64         0
pixel134     int64         0
pixel135     int64         0
pixel136     int64         0
pixel137     int64         0
pixel138     int64         0
pixel146     int64         0
pixel147     int64         0
pixel148     int64         0
pixel149     int64         0
pixel150     int64         0
pixel151     int64         0
pixel152     int64         0
pixel153     int64         0
pixel154     int64         0
pixel155     int64         0
pixel156     int64         0
pixel157     int64         0
pixel158     int64         0
pixel159     int64         0
pixel160     int64         0
pixel327     int64         0
pixel328     int64         0
pixel329     int64         0
pixel351     int64         0
pixel410     int64         0
pixel411     int64         0
pixel412     int64         0
pixel413     int64         0
pixel414     int64         0
pixel415     int64         0
pixel416     int64         0
pixel417     int64         0

In [4]:
# Split features and target variable
X = df.drop('label', axis=1)
y = df['label']

# Normalize the features
X = X / 255.0  # Pixel values range from 0 to 255

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
display(X_train)

,pixel43,pixel44,pixel92,pixel124,pixel125,pixel126,pixel127,pixel128,pixel129,pixel130,...,pixel329,pixel351,pixel410,pixel411,pixel412,pixel413,pixel414,pixel415,pixel416,pixel417
34941,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.992157,0.458824,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
24433,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.988235,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
24432,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.996078,0.000000,0.000000,0.000000,0.000000,0.592157,0.992157,0.000000,0.0,0.0
8832,0.0,0.0,0.0,0.000000,0.0,0.000000,0.321569,0.996078,0.874510,0.137255,...,0.000000,0.290196,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
30291,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.992157,0.996078,0.427451,0.000000,0.000000,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6265,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.086275,0.949020,0.309804,0.000000,0.000000,0.000000,0.000000,0.0,0.0
11284,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.113725,0.992157,...,0.988235,0.035294,0.000000,1.000000,0.992157,0.992157,0.329412,0.000000,0.0,0.0
38158,0.0,0.0,0.0,0.000000,0.0,0.749020,1.000000,0.501961,0.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.0,0.0
860,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.007843,0.639216,0.639216,0.529412,0.215686,0.003922,0.000000,0.000000,0.0,0.0
15795,0.0,0.0,0.0,0.062745,0.8,0.992157,0.847059,0.552941,0.113725,0.039216,...,0.992157,0.000000,0.000000,0.000000,0.443137,0.992157,0.988235,0.219608,0.0,0.0

In [6]:
display(y_train)

34941    9
24433    1
24432    7
8832     4
30291    8
        ..
6265     5
11284    0
38158    6
860      3
15795    0
Name: label, Length: 33600, dtype: int64

The reason we normalized the features by dividing by 255.0 is because the pixel values typically range from 0 to 255 in grayscale images. Normalizing the features to a range between 0 and 1 can help improve the convergence speed of the learning algorithm and make the model more numerically stable. This normalization ensures that all features contribute equally to the distance calculations performed by the KNN algorithm.

Normalization is performed on the pixel values themselves, not on the pixel positions represented by the label column. Therefore, we only need to normalize the feature matrix (X), not the target variable (y).

### Now, let's build the KNN model:

In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Initialize the KNN model
knn_model = KNeighborsClassifier(n_neighbors=5)

# Train the model
knn_model.fit(X_train, y_train)

# Make predictions
y_pred = knn_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of the KNN model: {accuracy:.4f}")

Accuracy of the KNN model: 0.6486

## Part 2: Building a Neural Network Model

Build a neural network model to predict handwriting. Discuss the accuracy and some of the challenges that you had.

Now, let's build the neural network model using TensorFlow/Keras to predict handwriting based on the provided dataset.:

In [ ]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

# Define the neural network architecture
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')  # 10 classes for digits 0 to 9
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.1)

# Evaluate the model
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Accuracy of the Neural Network model: {test_accuracy:.4f}")